algoritmo "Soma"
// Função :Soma entre dois numeros
// Autor :Gabriel Martins
// Data : 22/1/2022
// Seção de Declarações 
var
resultado,x ,y: real
inicio
// Seção de Comandos

escreval("Algoritmo de soma de dois numeros")
escreval("Digite o valor de X: ")
leia(x)

escreval("Digite o valor de Y: ")
leia(y)

resultado <- (x + y)

escreval("O resultado: ",resultado)
fimalgoritmo
